/*
 * This file is generated by jOOQ.
*/
package com.viridian.dummybank.gensrc.jooq.tables.records;


import com.viridian.dummybank.gensrc.jooq.tables.Autorizacion;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AutorizacionRecord extends UpdatableRecordImpl<AutorizacionRecord> implements Record3<Long, String, String> {

    private static final long serialVersionUID = 1453091366;

    /**
     * Setter for <code>viridianbank.Autorizacion.id_autorizacion</code>.
     */
    public void setIdAutorizacion(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>viridianbank.Autorizacion.id_autorizacion</code>.
     */
    public Long getIdAutorizacion() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>viridianbank.Autorizacion.tipo</code>.
     */
    public void setTipo(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>viridianbank.Autorizacion.tipo</code>.
     */
    public String getTipo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>viridianbank.Autorizacion.detalle</code>.
     */
    public void setDetalle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>viridianbank.Autorizacion.detalle</code>.
     */
    public String getDetalle() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Autorizacion.AUTORIZACION.ID_AUTORIZACION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Autorizacion.AUTORIZACION.TIPO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Autorizacion.AUTORIZACION.DETALLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getIdAutorizacion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTipo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDetalle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getIdAutorizacion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTipo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDetalle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AutorizacionRecord value1(Long value) {
        setIdAutorizacion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AutorizacionRecord value2(String value) {
        setTipo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AutorizacionRecord value3(String value) {
        setDetalle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AutorizacionRecord values(Long value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AutorizacionRecord
     */
    public AutorizacionRecord() {
        super(Autorizacion.AUTORIZACION);
    }

    /**
     * Create a detached, initialised AutorizacionRecord
     */
    public AutorizacionRecord(Long idAutorizacion, String tipo, String detalle) {
        super(Autorizacion.AUTORIZACION);

        set(0, idAutorizacion);
        set(1, tipo);
        set(2, detalle);
    }
}
