/*
 * This file is generated by jOOQ.
*/
package com.viridian.dummybank.gensrc.jooq.tables.records;


import com.viridian.dummybank.gensrc.jooq.tables.Beneficiario;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BeneficiarioRecord extends UpdatableRecordImpl<BeneficiarioRecord> implements Record7<Long, String, String, Long, Long, String, String> {

    private static final long serialVersionUID = 2015298751;

    /**
     * Setter for <code>viridianbank.Beneficiario.id_beneficiario</code>.
     */
    public void setIdBeneficiario(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>viridianbank.Beneficiario.id_beneficiario</code>.
     */
    public Long getIdBeneficiario() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>viridianbank.Beneficiario.nombre_rs</code>.
     */
    public void setNombreRs(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>viridianbank.Beneficiario.nombre_rs</code>.
     */
    public String getNombreRs() {
        return (String) get(1);
    }

    /**
     * Setter for <code>viridianbank.Beneficiario.nit_ci</code>.
     */
    public void setNitCi(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>viridianbank.Beneficiario.nit_ci</code>.
     */
    public String getNitCi() {
        return (String) get(2);
    }

    /**
     * Setter for <code>viridianbank.Beneficiario.numero_cuenta</code>.
     */
    public void setNumeroCuenta(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>viridianbank.Beneficiario.numero_cuenta</code>.
     */
    public Long getNumeroCuenta() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>viridianbank.Beneficiario.monto</code>.
     */
    public void setMonto(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>viridianbank.Beneficiario.monto</code>.
     */
    public Long getMonto() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>viridianbank.Beneficiario.moneda</code>.
     */
    public void setMoneda(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>viridianbank.Beneficiario.moneda</code>.
     */
    public String getMoneda() {
        return (String) get(5);
    }

    /**
     * Setter for <code>viridianbank.Beneficiario.banco</code>.
     */
    public void setBanco(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>viridianbank.Beneficiario.banco</code>.
     */
    public String getBanco() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, String, Long, Long, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, String, Long, Long, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Beneficiario.BENEFICIARIO.ID_BENEFICIARIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Beneficiario.BENEFICIARIO.NOMBRE_RS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Beneficiario.BENEFICIARIO.NIT_CI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return Beneficiario.BENEFICIARIO.NUMERO_CUENTA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Beneficiario.BENEFICIARIO.MONTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Beneficiario.BENEFICIARIO.MONEDA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Beneficiario.BENEFICIARIO.BANCO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getIdBeneficiario();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getNombreRs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getNitCi();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getNumeroCuenta();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getMonto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getMoneda();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getBanco();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getIdBeneficiario();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNombreRs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getNitCi();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getNumeroCuenta();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getMonto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getMoneda();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getBanco();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BeneficiarioRecord value1(Long value) {
        setIdBeneficiario(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BeneficiarioRecord value2(String value) {
        setNombreRs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BeneficiarioRecord value3(String value) {
        setNitCi(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BeneficiarioRecord value4(Long value) {
        setNumeroCuenta(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BeneficiarioRecord value5(Long value) {
        setMonto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BeneficiarioRecord value6(String value) {
        setMoneda(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BeneficiarioRecord value7(String value) {
        setBanco(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BeneficiarioRecord values(Long value1, String value2, String value3, Long value4, Long value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BeneficiarioRecord
     */
    public BeneficiarioRecord() {
        super(Beneficiario.BENEFICIARIO);
    }

    /**
     * Create a detached, initialised BeneficiarioRecord
     */
    public BeneficiarioRecord(Long idBeneficiario, String nombreRs, String nitCi, Long numeroCuenta, Long monto, String moneda, String banco) {
        super(Beneficiario.BENEFICIARIO);

        set(0, idBeneficiario);
        set(1, nombreRs);
        set(2, nitCi);
        set(3, numeroCuenta);
        set(4, monto);
        set(5, moneda);
        set(6, banco);
    }
}
