/*
 * This file is generated by jOOQ.
*/
package com.viridian.dummybank.gensrc.jooq.tables.records;


import com.viridian.dummybank.gensrc.jooq.tables.Cliente;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClienteRecord extends UpdatableRecordImpl<ClienteRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = 1755128315;

    /**
     * Setter for <code>viridianbank.Cliente.id_cliente</code>.
     */
    public void setIdCliente(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>viridianbank.Cliente.id_cliente</code>.
     */
    public Long getIdCliente() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>viridianbank.Cliente.tipo</code>.
     */
    public void setTipo(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>viridianbank.Cliente.tipo</code>.
     */
    public String getTipo() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Cliente.CLIENTE.ID_CLIENTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Cliente.CLIENTE.TIPO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getIdCliente();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTipo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getIdCliente();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTipo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value1(Long value) {
        setIdCliente(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value2(String value) {
        setTipo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClienteRecord
     */
    public ClienteRecord() {
        super(Cliente.CLIENTE);
    }

    /**
     * Create a detached, initialised ClienteRecord
     */
    public ClienteRecord(Long idCliente, String tipo) {
        super(Cliente.CLIENTE);

        set(0, idCliente);
        set(1, tipo);
    }
}
