/*
 * This file is generated by jOOQ.
*/
package com.viridian.dummybank.gensrc.jooq.tables.records;


import com.viridian.dummybank.gensrc.jooq.tables.Cuenta;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CuentaRecord extends UpdatableRecordImpl<CuentaRecord> implements Record5<Long, Long, String, Long, Long> {

    private static final long serialVersionUID = -762343698;

    /**
     * Setter for <code>viridianbank.cuenta.id_cuenta</code>.
     */
    public void setIdCuenta(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>viridianbank.cuenta.id_cuenta</code>.
     */
    public Long getIdCuenta() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>viridianbank.cuenta.numero_cuenta</code>.
     */
    public void setNumeroCuenta(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>viridianbank.cuenta.numero_cuenta</code>.
     */
    public Long getNumeroCuenta() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>viridianbank.cuenta.tipo</code>.
     */
    public void setTipo(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>viridianbank.cuenta.tipo</code>.
     */
    public String getTipo() {
        return (String) get(2);
    }

    /**
     * Setter for <code>viridianbank.cuenta.saldo</code>.
     */
    public void setSaldo(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>viridianbank.cuenta.saldo</code>.
     */
    public Long getSaldo() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>viridianbank.cuenta.cliente_id</code>.
     */
    public void setClienteId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>viridianbank.cuenta.cliente_id</code>.
     */
    public Long getClienteId() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Long, String, Long, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Long, String, Long, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Cuenta.CUENTA.ID_CUENTA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Cuenta.CUENTA.NUMERO_CUENTA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Cuenta.CUENTA.TIPO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return Cuenta.CUENTA.SALDO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Cuenta.CUENTA.CLIENTE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getIdCuenta();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getNumeroCuenta();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getTipo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getSaldo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getClienteId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getIdCuenta();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getNumeroCuenta();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTipo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getSaldo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getClienteId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CuentaRecord value1(Long value) {
        setIdCuenta(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CuentaRecord value2(Long value) {
        setNumeroCuenta(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CuentaRecord value3(String value) {
        setTipo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CuentaRecord value4(Long value) {
        setSaldo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CuentaRecord value5(Long value) {
        setClienteId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CuentaRecord values(Long value1, Long value2, String value3, Long value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CuentaRecord
     */
    public CuentaRecord() {
        super(Cuenta.CUENTA);
    }

    /**
     * Create a detached, initialised CuentaRecord
     */
    public CuentaRecord(Long idCuenta, Long numeroCuenta, String tipo, Long saldo, Long clienteId) {
        super(Cuenta.CUENTA);

        set(0, idCuenta);
        set(1, numeroCuenta);
        set(2, tipo);
        set(3, saldo);
        set(4, clienteId);
    }
}
