/*
 * This file is generated by jOOQ.
*/
package com.viridian.dummybank.gensrc.jooq.tables.records;


import com.viridian.dummybank.gensrc.jooq.tables.Estatus;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EstatusRecord extends UpdatableRecordImpl<EstatusRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = -1907528941;

    /**
     * Setter for <code>viridianbank.Estatus.id_estatus</code>.
     */
    public void setIdEstatus(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>viridianbank.Estatus.id_estatus</code>.
     */
    public Long getIdEstatus() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>viridianbank.Estatus.descripcion</code>.
     */
    public void setDescripcion(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>viridianbank.Estatus.descripcion</code>.
     */
    public String getDescripcion() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Estatus.ESTATUS.ID_ESTATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Estatus.ESTATUS.DESCRIPCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getIdEstatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getIdEstatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EstatusRecord value1(Long value) {
        setIdEstatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EstatusRecord value2(String value) {
        setDescripcion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EstatusRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EstatusRecord
     */
    public EstatusRecord() {
        super(Estatus.ESTATUS);
    }

    /**
     * Create a detached, initialised EstatusRecord
     */
    public EstatusRecord(Long idEstatus, String descripcion) {
        super(Estatus.ESTATUS);

        set(0, idEstatus);
        set(1, descripcion);
    }
}
