/*
 * This file is generated by jOOQ.
*/
package com.viridian.dummybank.gensrc.jooq.tables.records;


import com.viridian.dummybank.gensrc.jooq.tables.Metodo;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MetodoRecord extends UpdatableRecordImpl<MetodoRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = -810113759;

    /**
     * Setter for <code>viridianbank.Metodo.id_metodo</code>.
     */
    public void setIdMetodo(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>viridianbank.Metodo.id_metodo</code>.
     */
    public Long getIdMetodo() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>viridianbank.Metodo.descripcion</code>.
     */
    public void setDescripcion(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>viridianbank.Metodo.descripcion</code>.
     */
    public String getDescripcion() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Metodo.METODO.ID_METODO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Metodo.METODO.DESCRIPCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getIdMetodo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getIdMetodo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetodoRecord value1(Long value) {
        setIdMetodo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetodoRecord value2(String value) {
        setDescripcion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetodoRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MetodoRecord
     */
    public MetodoRecord() {
        super(Metodo.METODO);
    }

    /**
     * Create a detached, initialised MetodoRecord
     */
    public MetodoRecord(Long idMetodo, String descripcion) {
        super(Metodo.METODO);

        set(0, idMetodo);
        set(1, descripcion);
    }
}
