/*
 * This file is generated by jOOQ.
*/
package com.viridian.dummybank.gensrc.jooq.tables.records;


import com.viridian.dummybank.gensrc.jooq.tables.Operador;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OperadorRecord extends UpdatableRecordImpl<OperadorRecord> implements Record3<Long, String, Long> {

    private static final long serialVersionUID = 629057417;

    /**
     * Setter for <code>viridianbank.Operador.id_operador</code>.
     */
    public void setIdOperador(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>viridianbank.Operador.id_operador</code>.
     */
    public Long getIdOperador() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>viridianbank.Operador.nombre</code>.
     */
    public void setNombre(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>viridianbank.Operador.nombre</code>.
     */
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>viridianbank.Operador.usuario_id</code>.
     */
    public void setUsuarioId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>viridianbank.Operador.usuario_id</code>.
     */
    public Long getUsuarioId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Operador.OPERADOR.ID_OPERADOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Operador.OPERADOR.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Operador.OPERADOR.USUARIO_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getIdOperador();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getUsuarioId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getIdOperador();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getUsuarioId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OperadorRecord value1(Long value) {
        setIdOperador(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OperadorRecord value2(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OperadorRecord value3(Long value) {
        setUsuarioId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OperadorRecord values(Long value1, String value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OperadorRecord
     */
    public OperadorRecord() {
        super(Operador.OPERADOR);
    }

    /**
     * Create a detached, initialised OperadorRecord
     */
    public OperadorRecord(Long idOperador, String nombre, Long usuarioId) {
        super(Operador.OPERADOR);

        set(0, idOperador);
        set(1, nombre);
        set(2, usuarioId);
    }
}
