/*
 * This file is generated by jOOQ.
*/
package com.viridian.dummybank.gensrc.jooq.tables.records;


import com.viridian.dummybank.gensrc.jooq.tables.Operacion;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OperacionRecord extends UpdatableRecordImpl<OperacionRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = -1147626785;

    /**
     * Setter for <code>viridianbank.Operacion.id_operacion</code>.
     */
    public void setIdOperacion(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>viridianbank.Operacion.id_operacion</code>.
     */
    public Long getIdOperacion() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>viridianbank.Operacion.descripcion</code>.
     */
    public void setDescripcion(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>viridianbank.Operacion.descripcion</code>.
     */
    public String getDescripcion() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Operacion.OPERACION.ID_OPERACION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Operacion.OPERACION.DESCRIPCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getIdOperacion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getIdOperacion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OperacionRecord value1(Long value) {
        setIdOperacion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OperacionRecord value2(String value) {
        setDescripcion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OperacionRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OperacionRecord
     */
    public OperacionRecord() {
        super(Operacion.OPERACION);
    }

    /**
     * Create a detached, initialised OperacionRecord
     */
    public OperacionRecord(Long idOperacion, String descripcion) {
        super(Operacion.OPERACION);

        set(0, idOperacion);
        set(1, descripcion);
    }
}
