/*
 * This file is generated by jOOQ.
*/
package com.viridian.dummybank.gensrc.jooq.tables.records;


import com.viridian.dummybank.gensrc.jooq.tables.PersonaJuridica;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonaJuridicaRecord extends UpdatableRecordImpl<PersonaJuridicaRecord> implements Record5<Long, String, Long, String, Long> {

    private static final long serialVersionUID = 1542746859;

    /**
     * Setter for <code>viridianbank.Persona_Juridica.id_cliente</code>.
     */
    public void setIdCliente(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>viridianbank.Persona_Juridica.id_cliente</code>.
     */
    public Long getIdCliente() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>viridianbank.Persona_Juridica.nombre_razon</code>.
     */
    public void setNombreRazon(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>viridianbank.Persona_Juridica.nombre_razon</code>.
     */
    public String getNombreRazon() {
        return (String) get(1);
    }

    /**
     * Setter for <code>viridianbank.Persona_Juridica.nit</code>.
     */
    public void setNit(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>viridianbank.Persona_Juridica.nit</code>.
     */
    public Long getNit() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>viridianbank.Persona_Juridica.registro_fundaempresa</code>.
     */
    public void setRegistroFundaempresa(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>viridianbank.Persona_Juridica.registro_fundaempresa</code>.
     */
    public String getRegistroFundaempresa() {
        return (String) get(3);
    }

    /**
     * Setter for <code>viridianbank.Persona_Juridica.representante_legal</code>.
     */
    public void setRepresentanteLegal(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>viridianbank.Persona_Juridica.representante_legal</code>.
     */
    public Long getRepresentanteLegal() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, Long, String, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, Long, String, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PersonaJuridica.PERSONA_JURIDICA.ID_CLIENTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return PersonaJuridica.PERSONA_JURIDICA.NOMBRE_RAZON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return PersonaJuridica.PERSONA_JURIDICA.NIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return PersonaJuridica.PERSONA_JURIDICA.REGISTRO_FUNDAEMPRESA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return PersonaJuridica.PERSONA_JURIDICA.REPRESENTANTE_LEGAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getIdCliente();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getNombreRazon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getNit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getRegistroFundaempresa();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getRepresentanteLegal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getIdCliente();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNombreRazon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getNit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRegistroFundaempresa();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getRepresentanteLegal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonaJuridicaRecord value1(Long value) {
        setIdCliente(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonaJuridicaRecord value2(String value) {
        setNombreRazon(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonaJuridicaRecord value3(Long value) {
        setNit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonaJuridicaRecord value4(String value) {
        setRegistroFundaempresa(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonaJuridicaRecord value5(Long value) {
        setRepresentanteLegal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonaJuridicaRecord values(Long value1, String value2, Long value3, String value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PersonaJuridicaRecord
     */
    public PersonaJuridicaRecord() {
        super(PersonaJuridica.PERSONA_JURIDICA);
    }

    /**
     * Create a detached, initialised PersonaJuridicaRecord
     */
    public PersonaJuridicaRecord(Long idCliente, String nombreRazon, Long nit, String registroFundaempresa, Long representanteLegal) {
        super(PersonaJuridica.PERSONA_JURIDICA);

        set(0, idCliente);
        set(1, nombreRazon);
        set(2, nit);
        set(3, registroFundaempresa);
        set(4, representanteLegal);
    }
}
