/*
 * This file is generated by jOOQ.
*/
package com.viridian.dummybank.gensrc.jooq.tables.records;


import com.viridian.dummybank.gensrc.jooq.tables.Persona;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record20;
import org.jooq.Row20;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonaRecord extends UpdatableRecordImpl<PersonaRecord> implements Record20<Long, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = -594929760;

    /**
     * Setter for <code>viridianbank.Persona.id_persona</code>.
     */
    public void setIdPersona(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>viridianbank.Persona.id_persona</code>.
     */
    public Long getIdPersona() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>viridianbank.Persona.apellido_paterno</code>.
     */
    public void setApellidoPaterno(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>viridianbank.Persona.apellido_paterno</code>.
     */
    public String getApellidoPaterno() {
        return (String) get(1);
    }

    /**
     * Setter for <code>viridianbank.Persona.apellido_materno</code>.
     */
    public void setApellidoMaterno(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>viridianbank.Persona.apellido_materno</code>.
     */
    public String getApellidoMaterno() {
        return (String) get(2);
    }

    /**
     * Setter for <code>viridianbank.Persona.apellido_casado</code>.
     */
    public void setApellidoCasado(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>viridianbank.Persona.apellido_casado</code>.
     */
    public String getApellidoCasado() {
        return (String) get(3);
    }

    /**
     * Setter for <code>viridianbank.Persona.nombre</code>.
     */
    public void setNombre(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>viridianbank.Persona.nombre</code>.
     */
    public String getNombre() {
        return (String) get(4);
    }

    /**
     * Setter for <code>viridianbank.Persona.documento_identidad</code>.
     */
    public void setDocumentoIdentidad(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>viridianbank.Persona.documento_identidad</code>.
     */
    public String getDocumentoIdentidad() {
        return (String) get(5);
    }

    /**
     * Setter for <code>viridianbank.Persona.numero_documento</code>.
     */
    public void setNumeroDocumento(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>viridianbank.Persona.numero_documento</code>.
     */
    public String getNumeroDocumento() {
        return (String) get(6);
    }

    /**
     * Setter for <code>viridianbank.Persona.fecha_nacimiento</code>.
     */
    public void setFechaNacimiento(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>viridianbank.Persona.fecha_nacimiento</code>.
     */
    public String getFechaNacimiento() {
        return (String) get(7);
    }

    /**
     * Setter for <code>viridianbank.Persona.lugar_nacimiento</code>.
     */
    public void setLugarNacimiento(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>viridianbank.Persona.lugar_nacimiento</code>.
     */
    public String getLugarNacimiento() {
        return (String) get(8);
    }

    /**
     * Setter for <code>viridianbank.Persona.nacionalidad</code>.
     */
    public void setNacionalidad(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>viridianbank.Persona.nacionalidad</code>.
     */
    public String getNacionalidad() {
        return (String) get(9);
    }

    /**
     * Setter for <code>viridianbank.Persona.domicilio</code>.
     */
    public void setDomicilio(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>viridianbank.Persona.domicilio</code>.
     */
    public String getDomicilio() {
        return (String) get(10);
    }

    /**
     * Setter for <code>viridianbank.Persona.domicilio_trabajo</code>.
     */
    public void setDomicilioTrabajo(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>viridianbank.Persona.domicilio_trabajo</code>.
     */
    public String getDomicilioTrabajo() {
        return (String) get(11);
    }

    /**
     * Setter for <code>viridianbank.Persona.telefono</code>.
     */
    public void setTelefono(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>viridianbank.Persona.telefono</code>.
     */
    public String getTelefono() {
        return (String) get(12);
    }

    /**
     * Setter for <code>viridianbank.Persona.email</code>.
     */
    public void setEmail(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>viridianbank.Persona.email</code>.
     */
    public String getEmail() {
        return (String) get(13);
    }

    /**
     * Setter for <code>viridianbank.Persona.estado_civil</code>.
     */
    public void setEstadoCivil(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>viridianbank.Persona.estado_civil</code>.
     */
    public String getEstadoCivil() {
        return (String) get(14);
    }

    /**
     * Setter for <code>viridianbank.Persona.profesion</code>.
     */
    public void setProfesion(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>viridianbank.Persona.profesion</code>.
     */
    public String getProfesion() {
        return (String) get(15);
    }

    /**
     * Setter for <code>viridianbank.Persona.caracter_legal</code>.
     */
    public void setCaracterLegal(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>viridianbank.Persona.caracter_legal</code>.
     */
    public String getCaracterLegal() {
        return (String) get(16);
    }

    /**
     * Setter for <code>viridianbank.Persona.nombre_conyuge</code>.
     */
    public void setNombreConyuge(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>viridianbank.Persona.nombre_conyuge</code>.
     */
    public String getNombreConyuge() {
        return (String) get(17);
    }

    /**
     * Setter for <code>viridianbank.Persona.nombre_padre</code>.
     */
    public void setNombrePadre(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>viridianbank.Persona.nombre_padre</code>.
     */
    public String getNombrePadre() {
        return (String) get(18);
    }

    /**
     * Setter for <code>viridianbank.Persona.nombre_madre</code>.
     */
    public void setNombreMadre(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>viridianbank.Persona.nombre_madre</code>.
     */
    public String getNombreMadre() {
        return (String) get(19);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record20 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row20<Long, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row20) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row20<Long, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row20) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Persona.PERSONA.ID_PERSONA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Persona.PERSONA.APELLIDO_PATERNO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Persona.PERSONA.APELLIDO_MATERNO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Persona.PERSONA.APELLIDO_CASADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Persona.PERSONA.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Persona.PERSONA.DOCUMENTO_IDENTIDAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Persona.PERSONA.NUMERO_DOCUMENTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Persona.PERSONA.FECHA_NACIMIENTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Persona.PERSONA.LUGAR_NACIMIENTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Persona.PERSONA.NACIONALIDAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Persona.PERSONA.DOMICILIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Persona.PERSONA.DOMICILIO_TRABAJO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Persona.PERSONA.TELEFONO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return Persona.PERSONA.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return Persona.PERSONA.ESTADO_CIVIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return Persona.PERSONA.PROFESION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field17() {
        return Persona.PERSONA.CARACTER_LEGAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field18() {
        return Persona.PERSONA.NOMBRE_CONYUGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field19() {
        return Persona.PERSONA.NOMBRE_PADRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field20() {
        return Persona.PERSONA.NOMBRE_MADRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getIdPersona();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getApellidoPaterno();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getApellidoMaterno();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getApellidoCasado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getDocumentoIdentidad();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getNumeroDocumento();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getFechaNacimiento();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getLugarNacimiento();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getNacionalidad();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getDomicilio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getDomicilioTrabajo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getEstadoCivil();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component16() {
        return getProfesion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component17() {
        return getCaracterLegal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component18() {
        return getNombreConyuge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component19() {
        return getNombrePadre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component20() {
        return getNombreMadre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getIdPersona();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getApellidoPaterno();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getApellidoMaterno();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getApellidoCasado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDocumentoIdentidad();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getNumeroDocumento();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getFechaNacimiento();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getLugarNacimiento();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getNacionalidad();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getDomicilio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getDomicilioTrabajo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getEstadoCivil();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getProfesion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value17() {
        return getCaracterLegal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value18() {
        return getNombreConyuge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value19() {
        return getNombrePadre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value20() {
        return getNombreMadre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonaRecord value1(Long value) {
        setIdPersona(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonaRecord value2(String value) {
        setApellidoPaterno(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonaRecord value3(String value) {
        setApellidoMaterno(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonaRecord value4(String value) {
        setApellidoCasado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonaRecord value5(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonaRecord value6(String value) {
        setDocumentoIdentidad(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonaRecord value7(String value) {
        setNumeroDocumento(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonaRecord value8(String value) {
        setFechaNacimiento(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonaRecord value9(String value) {
        setLugarNacimiento(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonaRecord value10(String value) {
        setNacionalidad(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonaRecord value11(String value) {
        setDomicilio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonaRecord value12(String value) {
        setDomicilioTrabajo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonaRecord value13(String value) {
        setTelefono(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonaRecord value14(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonaRecord value15(String value) {
        setEstadoCivil(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonaRecord value16(String value) {
        setProfesion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonaRecord value17(String value) {
        setCaracterLegal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonaRecord value18(String value) {
        setNombreConyuge(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonaRecord value19(String value) {
        setNombrePadre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonaRecord value20(String value) {
        setNombreMadre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonaRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, String value15, String value16, String value17, String value18, String value19, String value20) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PersonaRecord
     */
    public PersonaRecord() {
        super(Persona.PERSONA);
    }

    /**
     * Create a detached, initialised PersonaRecord
     */
    public PersonaRecord(Long idPersona, String apellidoPaterno, String apellidoMaterno, String apellidoCasado, String nombre, String documentoIdentidad, String numeroDocumento, String fechaNacimiento, String lugarNacimiento, String nacionalidad, String domicilio, String domicilioTrabajo, String telefono, String email, String estadoCivil, String profesion, String caracterLegal, String nombreConyuge, String nombrePadre, String nombreMadre) {
        super(Persona.PERSONA);

        set(0, idPersona);
        set(1, apellidoPaterno);
        set(2, apellidoMaterno);
        set(3, apellidoCasado);
        set(4, nombre);
        set(5, documentoIdentidad);
        set(6, numeroDocumento);
        set(7, fechaNacimiento);
        set(8, lugarNacimiento);
        set(9, nacionalidad);
        set(10, domicilio);
        set(11, domicilioTrabajo);
        set(12, telefono);
        set(13, email);
        set(14, estadoCivil);
        set(15, profesion);
        set(16, caracterLegal);
        set(17, nombreConyuge);
        set(18, nombrePadre);
        set(19, nombreMadre);
    }
}
