/*
 * This file is generated by jOOQ.
*/
package com.viridian.dummybank.gensrc.jooq.tables.records;


import com.viridian.dummybank.gensrc.jooq.tables.Transaccion;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransaccionRecord extends UpdatableRecordImpl<TransaccionRecord> implements Record18<Long, Long, Timestamp, Timestamp, Timestamp, Long, Long, Long, Long, Long, String, Long, String, Long, Long, Long, Long, Long> {

    private static final long serialVersionUID = -249556116;

    /**
     * Setter for <code>viridianbank.Transaccion.id_transaccion</code>.
     */
    public void setIdTransaccion(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>viridianbank.Transaccion.id_transaccion</code>.
     */
    public Long getIdTransaccion() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>viridianbank.Transaccion.numero_cuenta</code>.
     */
    public void setNumeroCuenta(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>viridianbank.Transaccion.numero_cuenta</code>.
     */
    public Long getNumeroCuenta() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>viridianbank.Transaccion.fecha_inicio</code>.
     */
    public void setFechaInicio(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>viridianbank.Transaccion.fecha_inicio</code>.
     */
    public Timestamp getFechaInicio() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>viridianbank.Transaccion.fecha_aprobacion</code>.
     */
    public void setFechaAprobacion(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>viridianbank.Transaccion.fecha_aprobacion</code>.
     */
    public Timestamp getFechaAprobacion() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>viridianbank.Transaccion.fecha_ejecucion</code>.
     */
    public void setFechaEjecucion(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>viridianbank.Transaccion.fecha_ejecucion</code>.
     */
    public Timestamp getFechaEjecucion() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>viridianbank.Transaccion.numero_orden</code>.
     */
    public void setNumeroOrden(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>viridianbank.Transaccion.numero_orden</code>.
     */
    public Long getNumeroOrden() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>viridianbank.Transaccion.metodo_id</code>.
     */
    public void setMetodoId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>viridianbank.Transaccion.metodo_id</code>.
     */
    public Long getMetodoId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>viridianbank.Transaccion.estatus_id</code>.
     */
    public void setEstatusId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>viridianbank.Transaccion.estatus_id</code>.
     */
    public Long getEstatusId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>viridianbank.Transaccion.autorizacion_id</code>.
     */
    public void setAutorizacionId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>viridianbank.Transaccion.autorizacion_id</code>.
     */
    public Long getAutorizacionId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>viridianbank.Transaccion.operacion_id</code>.
     */
    public void setOperacionId(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>viridianbank.Transaccion.operacion_id</code>.
     */
    public Long getOperacionId() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>viridianbank.Transaccion.concepto_glosa</code>.
     */
    public void setConceptoGlosa(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>viridianbank.Transaccion.concepto_glosa</code>.
     */
    public String getConceptoGlosa() {
        return (String) get(10);
    }

    /**
     * Setter for <code>viridianbank.Transaccion.monto</code>.
     */
    public void setMonto(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>viridianbank.Transaccion.monto</code>.
     */
    public Long getMonto() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>viridianbank.Transaccion.moneda</code>.
     */
    public void setMoneda(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>viridianbank.Transaccion.moneda</code>.
     */
    public String getMoneda() {
        return (String) get(12);
    }

    /**
     * Setter for <code>viridianbank.Transaccion.saldo</code>.
     */
    public void setSaldo(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>viridianbank.Transaccion.saldo</code>.
     */
    public Long getSaldo() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>viridianbank.Transaccion.beneficiario_id</code>.
     */
    public void setBeneficiarioId(Long value) {
        set(14, value);
    }

    /**
     * Getter for <code>viridianbank.Transaccion.beneficiario_id</code>.
     */
    public Long getBeneficiarioId() {
        return (Long) get(14);
    }

    /**
     * Setter for <code>viridianbank.Transaccion.operador_id</code>.
     */
    public void setOperadorId(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>viridianbank.Transaccion.operador_id</code>.
     */
    public Long getOperadorId() {
        return (Long) get(15);
    }

    /**
     * Setter for <code>viridianbank.Transaccion.regis_asfi</code>.
     */
    public void setRegisAsfi(Long value) {
        set(16, value);
    }

    /**
     * Getter for <code>viridianbank.Transaccion.regis_asfi</code>.
     */
    public Long getRegisAsfi() {
        return (Long) get(16);
    }

    /**
     * Setter for <code>viridianbank.Transaccion.registro_facturacion</code>.
     */
    public void setRegistroFacturacion(Long value) {
        set(17, value);
    }

    /**
     * Getter for <code>viridianbank.Transaccion.registro_facturacion</code>.
     */
    public Long getRegistroFacturacion() {
        return (Long) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Long, Long, Timestamp, Timestamp, Timestamp, Long, Long, Long, Long, Long, String, Long, String, Long, Long, Long, Long, Long> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Long, Long, Timestamp, Timestamp, Timestamp, Long, Long, Long, Long, Long, String, Long, String, Long, Long, Long, Long, Long> valuesRow() {
        return (Row18) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Transaccion.TRANSACCION.ID_TRANSACCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Transaccion.TRANSACCION.NUMERO_CUENTA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Transaccion.TRANSACCION.FECHA_INICIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Transaccion.TRANSACCION.FECHA_APROBACION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Transaccion.TRANSACCION.FECHA_EJECUCION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return Transaccion.TRANSACCION.NUMERO_ORDEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return Transaccion.TRANSACCION.METODO_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return Transaccion.TRANSACCION.ESTATUS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return Transaccion.TRANSACCION.AUTORIZACION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return Transaccion.TRANSACCION.OPERACION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Transaccion.TRANSACCION.CONCEPTO_GLOSA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field12() {
        return Transaccion.TRANSACCION.MONTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Transaccion.TRANSACCION.MONEDA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field14() {
        return Transaccion.TRANSACCION.SALDO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field15() {
        return Transaccion.TRANSACCION.BENEFICIARIO_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field16() {
        return Transaccion.TRANSACCION.OPERADOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field17() {
        return Transaccion.TRANSACCION.REGIS_ASFI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field18() {
        return Transaccion.TRANSACCION.REGISTRO_FACTURACION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getIdTransaccion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getNumeroCuenta();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getFechaInicio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getFechaAprobacion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getFechaEjecucion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getNumeroOrden();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getMetodoId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component8() {
        return getEstatusId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component9() {
        return getAutorizacionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component10() {
        return getOperacionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getConceptoGlosa();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component12() {
        return getMonto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getMoneda();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component14() {
        return getSaldo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component15() {
        return getBeneficiarioId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component16() {
        return getOperadorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component17() {
        return getRegisAsfi();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component18() {
        return getRegistroFacturacion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getIdTransaccion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getNumeroCuenta();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getFechaInicio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getFechaAprobacion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getFechaEjecucion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getNumeroOrden();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getMetodoId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getEstatusId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getAutorizacionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getOperacionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getConceptoGlosa();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value12() {
        return getMonto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getMoneda();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value14() {
        return getSaldo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value15() {
        return getBeneficiarioId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value16() {
        return getOperadorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value17() {
        return getRegisAsfi();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value18() {
        return getRegistroFacturacion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransaccionRecord value1(Long value) {
        setIdTransaccion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransaccionRecord value2(Long value) {
        setNumeroCuenta(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransaccionRecord value3(Timestamp value) {
        setFechaInicio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransaccionRecord value4(Timestamp value) {
        setFechaAprobacion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransaccionRecord value5(Timestamp value) {
        setFechaEjecucion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransaccionRecord value6(Long value) {
        setNumeroOrden(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransaccionRecord value7(Long value) {
        setMetodoId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransaccionRecord value8(Long value) {
        setEstatusId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransaccionRecord value9(Long value) {
        setAutorizacionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransaccionRecord value10(Long value) {
        setOperacionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransaccionRecord value11(String value) {
        setConceptoGlosa(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransaccionRecord value12(Long value) {
        setMonto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransaccionRecord value13(String value) {
        setMoneda(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransaccionRecord value14(Long value) {
        setSaldo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransaccionRecord value15(Long value) {
        setBeneficiarioId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransaccionRecord value16(Long value) {
        setOperadorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransaccionRecord value17(Long value) {
        setRegisAsfi(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransaccionRecord value18(Long value) {
        setRegistroFacturacion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransaccionRecord values(Long value1, Long value2, Timestamp value3, Timestamp value4, Timestamp value5, Long value6, Long value7, Long value8, Long value9, Long value10, String value11, Long value12, String value13, Long value14, Long value15, Long value16, Long value17, Long value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransaccionRecord
     */
    public TransaccionRecord() {
        super(Transaccion.TRANSACCION);
    }

    /**
     * Create a detached, initialised TransaccionRecord
     */
    public TransaccionRecord(Long idTransaccion, Long numeroCuenta, Timestamp fechaInicio, Timestamp fechaAprobacion, Timestamp fechaEjecucion, Long numeroOrden, Long metodoId, Long estatusId, Long autorizacionId, Long operacionId, String conceptoGlosa, Long monto, String moneda, Long saldo, Long beneficiarioId, Long operadorId, Long regisAsfi, Long registroFacturacion) {
        super(Transaccion.TRANSACCION);

        set(0, idTransaccion);
        set(1, numeroCuenta);
        set(2, fechaInicio);
        set(3, fechaAprobacion);
        set(4, fechaEjecucion);
        set(5, numeroOrden);
        set(6, metodoId);
        set(7, estatusId);
        set(8, autorizacionId);
        set(9, operacionId);
        set(10, conceptoGlosa);
        set(11, monto);
        set(12, moneda);
        set(13, saldo);
        set(14, beneficiarioId);
        set(15, operadorId);
        set(16, regisAsfi);
        set(17, registroFacturacion);
    }
}
