/*
 * This file is generated by jOOQ.
*/
package com.viridian.dummybank.gensrc.jooq;


import com.viridian.dummybank.gensrc.jooq.tables.Autorizacion;
import com.viridian.dummybank.gensrc.jooq.tables.Beneficiario;
import com.viridian.dummybank.gensrc.jooq.tables.Cliente;
import com.viridian.dummybank.gensrc.jooq.tables.ClienteBeneficiario;
import com.viridian.dummybank.gensrc.jooq.tables.Cuenta;
import com.viridian.dummybank.gensrc.jooq.tables.Estatus;
import com.viridian.dummybank.gensrc.jooq.tables.Metodo;
import com.viridian.dummybank.gensrc.jooq.tables.Operacion;
import com.viridian.dummybank.gensrc.jooq.tables.Operador;
import com.viridian.dummybank.gensrc.jooq.tables.Persona;
import com.viridian.dummybank.gensrc.jooq.tables.PersonaJuridica;
import com.viridian.dummybank.gensrc.jooq.tables.PersonaNatural;
import com.viridian.dummybank.gensrc.jooq.tables.Transaccion;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in viridianbank
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>viridianbank.Autorizacion</code>.
     */
    public static final Autorizacion AUTORIZACION = com.viridian.dummybank.gensrc.jooq.tables.Autorizacion.AUTORIZACION;

    /**
     * The table <code>viridianbank.Beneficiario</code>.
     */
    public static final Beneficiario BENEFICIARIO = com.viridian.dummybank.gensrc.jooq.tables.Beneficiario.BENEFICIARIO;

    /**
     * The table <code>viridianbank.Cliente</code>.
     */
    public static final Cliente CLIENTE = com.viridian.dummybank.gensrc.jooq.tables.Cliente.CLIENTE;

    /**
     * The table <code>viridianbank.Cliente_Beneficiario</code>.
     */
    public static final ClienteBeneficiario CLIENTE_BENEFICIARIO = com.viridian.dummybank.gensrc.jooq.tables.ClienteBeneficiario.CLIENTE_BENEFICIARIO;

    /**
     * The table <code>viridianbank.cuenta</code>.
     */
    public static final Cuenta CUENTA = com.viridian.dummybank.gensrc.jooq.tables.Cuenta.CUENTA;

    /**
     * The table <code>viridianbank.Estatus</code>.
     */
    public static final Estatus ESTATUS = com.viridian.dummybank.gensrc.jooq.tables.Estatus.ESTATUS;

    /**
     * The table <code>viridianbank.Metodo</code>.
     */
    public static final Metodo METODO = com.viridian.dummybank.gensrc.jooq.tables.Metodo.METODO;

    /**
     * The table <code>viridianbank.Operacion</code>.
     */
    public static final Operacion OPERACION = com.viridian.dummybank.gensrc.jooq.tables.Operacion.OPERACION;

    /**
     * The table <code>viridianbank.Operador</code>.
     */
    public static final Operador OPERADOR = com.viridian.dummybank.gensrc.jooq.tables.Operador.OPERADOR;

    /**
     * The table <code>viridianbank.Persona</code>.
     */
    public static final Persona PERSONA = com.viridian.dummybank.gensrc.jooq.tables.Persona.PERSONA;

    /**
     * The table <code>viridianbank.Persona_Juridica</code>.
     */
    public static final PersonaJuridica PERSONA_JURIDICA = com.viridian.dummybank.gensrc.jooq.tables.PersonaJuridica.PERSONA_JURIDICA;

    /**
     * The table <code>viridianbank.Persona_Natural</code>.
     */
    public static final PersonaNatural PERSONA_NATURAL = com.viridian.dummybank.gensrc.jooq.tables.PersonaNatural.PERSONA_NATURAL;

    /**
     * The table <code>viridianbank.Transaccion</code>.
     */
    public static final Transaccion TRANSACCION = com.viridian.dummybank.gensrc.jooq.tables.Transaccion.TRANSACCION;
}
