/*
 * This file is generated by jOOQ.
*/
package com.viridian.dummybank.gensrc.jooq.tables;


import com.viridian.dummybank.gensrc.jooq.Indexes;
import com.viridian.dummybank.gensrc.jooq.Keys;
import com.viridian.dummybank.gensrc.jooq.Viridianbank;
import com.viridian.dummybank.gensrc.jooq.tables.records.AutorizacionRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Autorizacion extends TableImpl<AutorizacionRecord> {

    private static final long serialVersionUID = -225236643;

    /**
     * The reference instance of <code>viridianbank.Autorizacion</code>
     */
    public static final Autorizacion AUTORIZACION = new Autorizacion();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AutorizacionRecord> getRecordType() {
        return AutorizacionRecord.class;
    }

    /**
     * The column <code>viridianbank.Autorizacion.id_autorizacion</code>.
     */
    public final TableField<AutorizacionRecord, Long> ID_AUTORIZACION = createField("id_autorizacion", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>viridianbank.Autorizacion.tipo</code>.
     */
    public final TableField<AutorizacionRecord, String> TIPO = createField("tipo", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>viridianbank.Autorizacion.detalle</code>.
     */
    public final TableField<AutorizacionRecord, String> DETALLE = createField("detalle", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * Create a <code>viridianbank.Autorizacion</code> table reference
     */
    public Autorizacion() {
        this(DSL.name("Autorizacion"), null);
    }

    /**
     * Create an aliased <code>viridianbank.Autorizacion</code> table reference
     */
    public Autorizacion(String alias) {
        this(DSL.name(alias), AUTORIZACION);
    }

    /**
     * Create an aliased <code>viridianbank.Autorizacion</code> table reference
     */
    public Autorizacion(Name alias) {
        this(alias, AUTORIZACION);
    }

    private Autorizacion(Name alias, Table<AutorizacionRecord> aliased) {
        this(alias, aliased, null);
    }

    private Autorizacion(Name alias, Table<AutorizacionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Viridianbank.VIRIDIANBANK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.AUTORIZACION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AutorizacionRecord, Long> getIdentity() {
        return Keys.IDENTITY_AUTORIZACION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AutorizacionRecord> getPrimaryKey() {
        return Keys.KEY_AUTORIZACION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AutorizacionRecord>> getKeys() {
        return Arrays.<UniqueKey<AutorizacionRecord>>asList(Keys.KEY_AUTORIZACION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Autorizacion as(String alias) {
        return new Autorizacion(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Autorizacion as(Name alias) {
        return new Autorizacion(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Autorizacion rename(String name) {
        return new Autorizacion(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Autorizacion rename(Name name) {
        return new Autorizacion(name, null);
    }
}
