/*
 * This file is generated by jOOQ.
*/
package com.viridian.dummybank.gensrc.jooq.tables;


import com.viridian.dummybank.gensrc.jooq.Indexes;
import com.viridian.dummybank.gensrc.jooq.Keys;
import com.viridian.dummybank.gensrc.jooq.Viridianbank;
import com.viridian.dummybank.gensrc.jooq.tables.records.BeneficiarioRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Beneficiario extends TableImpl<BeneficiarioRecord> {

    private static final long serialVersionUID = -1102345398;

    /**
     * The reference instance of <code>viridianbank.Beneficiario</code>
     */
    public static final Beneficiario BENEFICIARIO = new Beneficiario();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BeneficiarioRecord> getRecordType() {
        return BeneficiarioRecord.class;
    }

    /**
     * The column <code>viridianbank.Beneficiario.id_beneficiario</code>.
     */
    public final TableField<BeneficiarioRecord, Long> ID_BENEFICIARIO = createField("id_beneficiario", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>viridianbank.Beneficiario.nombre_rs</code>.
     */
    public final TableField<BeneficiarioRecord, String> NOMBRE_RS = createField("nombre_rs", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>viridianbank.Beneficiario.nit_ci</code>.
     */
    public final TableField<BeneficiarioRecord, String> NIT_CI = createField("nit_ci", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>viridianbank.Beneficiario.numero_cuenta</code>.
     */
    public final TableField<BeneficiarioRecord, Long> NUMERO_CUENTA = createField("numero_cuenta", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>viridianbank.Beneficiario.monto</code>.
     */
    public final TableField<BeneficiarioRecord, Long> MONTO = createField("monto", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>viridianbank.Beneficiario.moneda</code>.
     */
    public final TableField<BeneficiarioRecord, String> MONEDA = createField("moneda", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>viridianbank.Beneficiario.banco</code>.
     */
    public final TableField<BeneficiarioRecord, String> BANCO = createField("banco", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * Create a <code>viridianbank.Beneficiario</code> table reference
     */
    public Beneficiario() {
        this(DSL.name("Beneficiario"), null);
    }

    /**
     * Create an aliased <code>viridianbank.Beneficiario</code> table reference
     */
    public Beneficiario(String alias) {
        this(DSL.name(alias), BENEFICIARIO);
    }

    /**
     * Create an aliased <code>viridianbank.Beneficiario</code> table reference
     */
    public Beneficiario(Name alias) {
        this(alias, BENEFICIARIO);
    }

    private Beneficiario(Name alias, Table<BeneficiarioRecord> aliased) {
        this(alias, aliased, null);
    }

    private Beneficiario(Name alias, Table<BeneficiarioRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Viridianbank.VIRIDIANBANK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.BENEFICIARIO_NIT_CI, Indexes.BENEFICIARIO_NUMERO_CUENTA, Indexes.BENEFICIARIO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<BeneficiarioRecord, Long> getIdentity() {
        return Keys.IDENTITY_BENEFICIARIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BeneficiarioRecord> getPrimaryKey() {
        return Keys.KEY_BENEFICIARIO_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BeneficiarioRecord>> getKeys() {
        return Arrays.<UniqueKey<BeneficiarioRecord>>asList(Keys.KEY_BENEFICIARIO_PRIMARY, Keys.KEY_BENEFICIARIO_NIT_CI, Keys.KEY_BENEFICIARIO_NUMERO_CUENTA);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Beneficiario as(String alias) {
        return new Beneficiario(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Beneficiario as(Name alias) {
        return new Beneficiario(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Beneficiario rename(String name) {
        return new Beneficiario(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Beneficiario rename(Name name) {
        return new Beneficiario(name, null);
    }
}
