/*
 * This file is generated by jOOQ.
*/
package com.viridian.dummybank.gensrc.jooq.tables;


import com.viridian.dummybank.gensrc.jooq.Indexes;
import com.viridian.dummybank.gensrc.jooq.Keys;
import com.viridian.dummybank.gensrc.jooq.Viridianbank;
import com.viridian.dummybank.gensrc.jooq.tables.records.ClienteBeneficiarioRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClienteBeneficiario extends TableImpl<ClienteBeneficiarioRecord> {

    private static final long serialVersionUID = 1176716157;

    /**
     * The reference instance of <code>viridianbank.Cliente_Beneficiario</code>
     */
    public static final ClienteBeneficiario CLIENTE_BENEFICIARIO = new ClienteBeneficiario();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClienteBeneficiarioRecord> getRecordType() {
        return ClienteBeneficiarioRecord.class;
    }

    /**
     * The column <code>viridianbank.Cliente_Beneficiario.cliente_id</code>.
     */
    public final TableField<ClienteBeneficiarioRecord, Long> CLIENTE_ID = createField("cliente_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>viridianbank.Cliente_Beneficiario.beneficiario_id</code>.
     */
    public final TableField<ClienteBeneficiarioRecord, Long> BENEFICIARIO_ID = createField("beneficiario_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>viridianbank.Cliente_Beneficiario</code> table reference
     */
    public ClienteBeneficiario() {
        this(DSL.name("Cliente_Beneficiario"), null);
    }

    /**
     * Create an aliased <code>viridianbank.Cliente_Beneficiario</code> table reference
     */
    public ClienteBeneficiario(String alias) {
        this(DSL.name(alias), CLIENTE_BENEFICIARIO);
    }

    /**
     * Create an aliased <code>viridianbank.Cliente_Beneficiario</code> table reference
     */
    public ClienteBeneficiario(Name alias) {
        this(alias, CLIENTE_BENEFICIARIO);
    }

    private ClienteBeneficiario(Name alias, Table<ClienteBeneficiarioRecord> aliased) {
        this(alias, aliased, null);
    }

    private ClienteBeneficiario(Name alias, Table<ClienteBeneficiarioRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Viridianbank.VIRIDIANBANK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CLIENTE_BENEFICIARIO_BENEFICIARIO_ID, Indexes.CLIENTE_BENEFICIARIO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ClienteBeneficiarioRecord> getPrimaryKey() {
        return Keys.KEY_CLIENTE_BENEFICIARIO_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ClienteBeneficiarioRecord>> getKeys() {
        return Arrays.<UniqueKey<ClienteBeneficiarioRecord>>asList(Keys.KEY_CLIENTE_BENEFICIARIO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ClienteBeneficiarioRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ClienteBeneficiarioRecord, ?>>asList(Keys.CLIENTE_BENEFICIARIO_IBFK_1, Keys.CLIENTE_BENEFICIARIO_IBFK_2);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteBeneficiario as(String alias) {
        return new ClienteBeneficiario(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteBeneficiario as(Name alias) {
        return new ClienteBeneficiario(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ClienteBeneficiario rename(String name) {
        return new ClienteBeneficiario(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClienteBeneficiario rename(Name name) {
        return new ClienteBeneficiario(name, null);
    }
}
