/*
 * This file is generated by jOOQ.
*/
package com.viridian.dummybank.gensrc.jooq.tables;


import com.viridian.dummybank.gensrc.jooq.Indexes;
import com.viridian.dummybank.gensrc.jooq.Keys;
import com.viridian.dummybank.gensrc.jooq.Viridianbank;
import com.viridian.dummybank.gensrc.jooq.tables.records.EstatusRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Estatus extends TableImpl<EstatusRecord> {

    private static final long serialVersionUID = 919808298;

    /**
     * The reference instance of <code>viridianbank.Estatus</code>
     */
    public static final Estatus ESTATUS = new Estatus();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EstatusRecord> getRecordType() {
        return EstatusRecord.class;
    }

    /**
     * The column <code>viridianbank.Estatus.id_estatus</code>.
     */
    public final TableField<EstatusRecord, Long> ID_ESTATUS = createField("id_estatus", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>viridianbank.Estatus.descripcion</code>.
     */
    public final TableField<EstatusRecord, String> DESCRIPCION = createField("descripcion", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * Create a <code>viridianbank.Estatus</code> table reference
     */
    public Estatus() {
        this(DSL.name("Estatus"), null);
    }

    /**
     * Create an aliased <code>viridianbank.Estatus</code> table reference
     */
    public Estatus(String alias) {
        this(DSL.name(alias), ESTATUS);
    }

    /**
     * Create an aliased <code>viridianbank.Estatus</code> table reference
     */
    public Estatus(Name alias) {
        this(alias, ESTATUS);
    }

    private Estatus(Name alias, Table<EstatusRecord> aliased) {
        this(alias, aliased, null);
    }

    private Estatus(Name alias, Table<EstatusRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Viridianbank.VIRIDIANBANK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ESTATUS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<EstatusRecord, Long> getIdentity() {
        return Keys.IDENTITY_ESTATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<EstatusRecord> getPrimaryKey() {
        return Keys.KEY_ESTATUS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<EstatusRecord>> getKeys() {
        return Arrays.<UniqueKey<EstatusRecord>>asList(Keys.KEY_ESTATUS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Estatus as(String alias) {
        return new Estatus(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Estatus as(Name alias) {
        return new Estatus(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Estatus rename(String name) {
        return new Estatus(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Estatus rename(Name name) {
        return new Estatus(name, null);
    }
}
