/*
 * This file is generated by jOOQ.
*/
package com.viridian.dummybank.gensrc.jooq.tables;


import com.viridian.dummybank.gensrc.jooq.Indexes;
import com.viridian.dummybank.gensrc.jooq.Keys;
import com.viridian.dummybank.gensrc.jooq.Viridianbank;
import com.viridian.dummybank.gensrc.jooq.tables.records.OperacionRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Operacion extends TableImpl<OperacionRecord> {

    private static final long serialVersionUID = -1962283169;

    /**
     * The reference instance of <code>viridianbank.Operacion</code>
     */
    public static final Operacion OPERACION = new Operacion();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OperacionRecord> getRecordType() {
        return OperacionRecord.class;
    }

    /**
     * The column <code>viridianbank.Operacion.id_operacion</code>.
     */
    public final TableField<OperacionRecord, Long> ID_OPERACION = createField("id_operacion", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>viridianbank.Operacion.descripcion</code>.
     */
    public final TableField<OperacionRecord, String> DESCRIPCION = createField("descripcion", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * Create a <code>viridianbank.Operacion</code> table reference
     */
    public Operacion() {
        this(DSL.name("Operacion"), null);
    }

    /**
     * Create an aliased <code>viridianbank.Operacion</code> table reference
     */
    public Operacion(String alias) {
        this(DSL.name(alias), OPERACION);
    }

    /**
     * Create an aliased <code>viridianbank.Operacion</code> table reference
     */
    public Operacion(Name alias) {
        this(alias, OPERACION);
    }

    private Operacion(Name alias, Table<OperacionRecord> aliased) {
        this(alias, aliased, null);
    }

    private Operacion(Name alias, Table<OperacionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Viridianbank.VIRIDIANBANK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.OPERACION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<OperacionRecord, Long> getIdentity() {
        return Keys.IDENTITY_OPERACION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OperacionRecord> getPrimaryKey() {
        return Keys.KEY_OPERACION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OperacionRecord>> getKeys() {
        return Arrays.<UniqueKey<OperacionRecord>>asList(Keys.KEY_OPERACION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Operacion as(String alias) {
        return new Operacion(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Operacion as(Name alias) {
        return new Operacion(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Operacion rename(String name) {
        return new Operacion(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Operacion rename(Name name) {
        return new Operacion(name, null);
    }
}
